### ISSUE TITLE
"const" type modifier is missing in auto-completed keyword list

### ISSUE THREAD

**Issue by JSeb-92** [tgjones/HlslTools#98] opened 2017-06-12 08:03 UTC
Hi,

I use to write "const" on some shader (internal) variables , and it always auto-complete my typing to "ConstructGSWithSO" since "const" is missing in the list.
Then I've to hit 'esc' to avoid ending with a wrong big keyword.
Could you add "const" to your auto-complete keyword list, please ?
Thanks

**Comment by tgjones** [comment] 2017-08-31 11:08
Closing this as a dupe of #36 - currently, *no* keywords are completed, so that whole feature needs to be implemented.

**Closed by tgjones** 2017-08-31 11:08 UTC
