### ISSUE TITLE
How to disable Preprocessor support;

### ISSUE THREAD

**Issue by asdMild** [tgjones/HlslTools#125] opened 2018-07-31 14:48 UTC
Preprocessor support is not work well for the shader in ue4

**Comment by tiantian20007** [comment] 2019-06-18 07:14
Came across the same issue.
Is there a way to just disable the function that "Gray out code excluded by preprocessor" ?

**Comment by tgjones** [comment] 2019-07-03 17:59
The problem is this:

1. The syntax highlighting in HLSL Tools is derived from the AST - in other words, from knowledge of the parsed code and what each token in the code means, and
2. The parser completely skips over code that is excluded by the preprocessor.

This is the same thing that Roslyn (the C# compiler) does, so for the same reason it's impossible in Visual Studio to turn this feature off for C# code.

So it's not a case of disabling the feature - the information about how to syntax highlight the excluded code simply isn't there.

I've been looking at alternate methods of syntax highlighting but haven't found yet anything workable yet. Closing this for now unless someone comes up with a good way to implement it.

**Closed by tgjones** 2019-07-03 17:59 UTC
