### ISSUE TITLE
Unity bugs: wrong autocomplete

### ISSUE THREAD

**Issue by Lex-DRL** [tgjones/HlslTools#114] opened 2017-10-21 22:57 UTC
Some of the syntax entities are not recognized by HLSL tools, which cause bugs.
Basically, there are two main areas of the problem:

### 1. the `fixed` type
![001](https://user-images.githubusercontent.com/3897975/31856429-99827fbe-b6c9-11e7-932a-b16c2aeed446.png)
Meanwhile, `half` is properly detected, though both these types are overridden in HLSLSupport.cginc (which is included from UnityCG.cginc).
![002](https://user-images.githubusercontent.com/3897975/31856461-45230a5a-b6ca-11e7-9961-5476fccab700.png)

### 2. Variable names (at least some of them)
This bug is even worse because it breaks your code. :cry: 
The simplest scenario to reproduce:

1. Create a default `Unlit Shader` preset.
2. Open it.
3. Try to set any component of the defult `o` variable (output from vert function).
![003](https://user-images.githubusercontent.com/3897975/31856483-c4486398-b6ca-11e7-95ad-a13912d0e9e2.png)
The `o` isn't anywhere on the autocompletions list. So as soon as you type dot, you have `o` replaced with whatever name was the closest... except for the only name you need that's defined a few lines above:
![004](https://user-images.githubusercontent.com/3897975/31856496-171413b0-b6cb-11e7-9e3c-e638ec785d34.png)
But if you perform an "o-escape-dot" jump through the hoop, then you see that the variable is actually detected, and HLSL tools can see it's contents:
![05](https://user-images.githubusercontent.com/3897975/31856519-808b457a-b6cb-11e7-9445-0f4154c62e99.png)
... but somehow can't suggest `o` itself.

**Comment by dorodo95** [comment] 2018-01-24 03:43
Nothing on this? Would love to see some more integration with Unity :)

**Comment by Lex-DRL** [comment] 2018-06-12 21:56
@tgjones is there any update on this issue?

**Comment by tgjones** [comment] 2018-11-04 23:42
@Lex-DRL sorry for the massive delay in replying. I've been busy in my personal life and not able to give much time to this project.

I guess in the screenshots above, that the HLSL code is embedded in `CGPROGRAM` blocks in a Unity `.shader` file?

**Comment by tgjones** [comment] 2019-07-03 18:11
This bug is now almost 2 years old! Oops.

(1) is a dupe of #93. `fixed` is defined in a macro (`#define fixed half`), and HLSL Tools doesn't yet have completion for macros.

(2) was a subtle bug, but I think I've fixed it in 7a4bdcac382fa9611eb2bb50cd83b63ee35f3c9e.

**Closed by tgjones** 2019-07-03 18:11 UTC
