### ISSUE TITLE
Autocomplete erroneously replaces language keywords

### ISSUE THREAD

**Issue by Friendly0Fire** [tgjones/HlslTools#112] opened 2017-09-06 17:52 UTC
* Visual Studio 2015 Enterprise
* Only third party extension installed aside from this is P4VS
* Editing .usf (Unreal shaders, still compliant HLSL though) files
* Tried nightly and VS Gallery version

Steps to reproduce:
1. With Intellisense on, try entering certain HLSL keywords (definitely happens with in, out and all of the rgbaxyzw single-letter accessors) and pressing space or enter.
2. Rather than keeping the keyword in place, autocomplete will replace it with something (could be a type, could be a variable, anything in the list) instead.

**Comment by AdamJMiles** [comment] 2017-09-09 23:54
I'm experiencing some rather awkward autocomplete too. Would this be an example of what you're talking about @Friendly0Fire ?

![image](https://user-images.githubusercontent.com/18439438/30244972-a6350e16-95c2-11e7-9ce3-01cf5918f6d2.png)

**Comment by Friendly0Fire** [comment] 2017-09-11 16:48
Yep! It's also happening when I try typing eg somefloat4.xy, it'll try to autocomplete the xy away to some random thing.

Even for things I _want_ autocomplete on, it has a tendency to go find something oddly distant, like picking an obscure built-in function that barely matches instead of the local variable that shares the same first 8 letters as what I typed.

**Comment by PathogenDavid** [comment] 2017-09-13 08:43
This is a duplicate of #36. The main issue is that HLSL tools isn't aware of language keywords at all.

It's obviously far from ideal, but I've gotten into the habit of pressing escape to cancel the Intellisense prompt whenever I'm typing a language keyword.

**Comment by tgjones** [comment] 2019-07-03 17:13
Closing this as a dupe of #36. Keyword completion is really important to add.

**Closed by tgjones** 2019-07-03 17:13 UTC
