### ISSUE TITLE
Autocomplete doubles up first letter

### ISSUE THREAD

**Issue by Friendly0Fire** [tgjones/HlslTools#111] opened 2017-09-06 17:49 UTC
* Visual Studio 2015 Enterprise
* Only third party extension installed aside from this is P4VS
* Editing .usf (Unreal shaders, still compliant HLSL though) files
* Tried nightly and VS Gallery version

Steps to reproduce:
1. With Intellisense on, type a variable or function name.
2. When autocomplete shows up, select any of the suggestions.
3. The first letter will be doubled up, e.g.  CalcSceneColorAndDepth becomes CCalcSceneColorAndDepth.

**Comment by AdamJMiles** [comment] 2017-09-10 00:32
I can confirm I'm affected by this too.

**Comment by PathogenDavid** [comment] 2017-09-11 21:18
I can also confirm this is happening with Visual Studio 2017.

Specifically, it seems that this happens with symbols that start with an uppercase letter, and only if you start by typing that first letter as uppercase. (For example, if the actual symbol is `InputChunk` and you type `inp` it is fine, but if you type `Inp` it breaks.)

I've narrowed down that this issue was introduced in 1.1.266, which includes the following commits:

- [Finish implementing completion in Features / EditorFeatures / LanguageServer](https://github.com/tgjones/HlslTools/commit/27de936638ed125200dcad4f4b70330c1123a0ab)
- [Move completion tests to new HLSL features test project](https://github.com/tgjones/HlslTools/commit/4ff4599efbfe49f48460b6d1ca9c98da3db96f2f)

Since the latter commit is only related to the tests, I'm inclined to believe the former is the culprit.

Those wishing to get the last version of the extension before the issue was introduced can find it on AppVeyor: https://ci.appveyor.com/project/tgjones/hlsltools/build/1.1.265/artifacts

**Comment by Friendly0Fire** [comment] 2017-09-15 17:43
Hmm, I don't know if the install failed but I tried using that version and I still get the bug.

**Comment by PathogenDavid** [comment] 2017-09-18 20:40
You might need to uninstall the gallery version and disable automatic extension updates. (You will start receiving manual update notifications instead.) You should also double-check the version number that Visual Studio thinks is installed under Tools > Extensions and Updates.

**Comment by Lex-DRL** [comment] 2017-10-21 23:10
I confirm the same issue in VS Community 2015 Update 3, in Unity-style shader (ShaderLab wrapping around HLSL), with the latest ext version (1.1.272).

**Comment by Flave229** [comment] 2017-11-16 20:27
I can confirm this is also broken on VS Enterprise 2017 version 15.4.2
Using HLSL tool version 1.1.272

Any fix inbound to address this?

**Comment by BenjaminHolland** [comment] 2017-12-07 05:01
Also can confirm,
Ext. Version 1.1.272
VS Version 15.4.5

**Comment by dkudrin** [comment] 2019-06-11 19:07
This bug is still there.
UE4 .usf files

- VS Community 2017 (can't work with UE Engine in 2019) 15.9.12
- HLSL Ext. Version 1.1.272

**Comment by tgjones** [comment] 2019-07-07 20:41
Fixed by https://github.com/tgjones/HlslTools/commit/461385b349d909a661e210077fe1b6435d3575f5#diff-7eca9edd2fd844942ba8634f4eb885ba.

**Closed by tgjones** 2019-07-07 20:41 UTC
