### ISSUE TITLE
Crash when opening Formatting settings in Visual Studio 2017

### ISSUE THREAD

**Issue by razveck** [tgjones/HlslTools#119] opened 2018-03-14 12:34 UTC
Whenever I click any of the options under Formatting, Visual Studio crashes.
![image](https://user-images.githubusercontent.com/16647581/37402549-4c72b714-278c-11e8-8c10-ae0b73aee0e2.png)

I can however click on the Formatting label itself and change the options within.

**Comment by redorav** [comment] 2018-03-28 10:30
I can confirm this is happening to me too

**Comment by BoltManGuy** [comment] 2018-04-01 08:59
Definitely having this problem but worse than described. upon first installing the extension i can access these settings but after trying to change one it pops up an error but otherwise works fine and saves the settings changes and it all works. that isssss until you restart visual studio and the formatting of the entire extension is completely broken and throws errors any time it tries to autoformat. and then ofc this is where if you try going back into the formatting settings it hangs and crashes. its like it corrupts the settings and the only fix is to hard delete files and stuff. which is super annoying.

i guess ill just put up with lame new line brackets for now. tho it doesnt seem this extension is going to get updated by the creator any time soon.

**Comment by tgjones** [comment] 2018-11-04 23:45
Thanks for reporting this! Closing this in favour of #113, which looks like the same issue.

**Closed by tgjones** 2018-11-04 23:45 UTC
