### ISSUE TITLE
Last version crash (1.1.300)

### ISSUE THREAD

**Issue by JSeb-92** [tgjones/HlslTools#186] opened 2020-02-14 16:55 UTC
---------------------------
Microsoft Visual Studio
---------------------------
An exception has been encountered. This may be caused by an extension.

You can get more information by examining the file 'C:\Users\JSeb!\AppData\Roaming\Microsoft\VisualStudio\15.0_338878c3\ActivityLog.xml'.

Hello,
Please find the ActivityLog.xml file in the attached zip
Regards

[ActivityLog.zip](https://github.com/tgjones/HlslTools/files/4205584/ActivityLog.zip)

**Comment by tgjones** [comment] 2020-02-15 21:58
Thanks - it looks like a duplicate of #180, which I've already fixed, but apparently I haven't done a release since then. I'll try to do a new release today.

**Closed by tgjones** 2020-02-15 21:58 UTC

**Comment by tgjones** [comment] 2020-02-15 23:10
I've just released 1.1.301 which should fix this issue.

**Comment by JSeb-92** [comment] 2020-02-24 12:28
Indeed it no longer crash, thanks
