### ISSUE TITLE
ShaderTools.CodeAnalysis.Workspace.CheckDocumentIsOpen exception

### ISSUE THREAD

**Issue by kornman00** [tgjones/HlslTools#163] opened 2019-07-29 07:05 UTC
Seems related to #113 maybe? I just installed this extension (1.1.296) for VS2017 after encountering the LegacySitePackage exception I reported yesterday, so I browsed through all the HLSL options to see what was available and make any tweaks. After hitting OK, I hit the exception below. If it helps, I had a SLN open with a single C++ project open (with all my fx files in it).

```
  <entry>
    <record>2364</record>
    <time>2019/07/29 06:55:57.304</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: &apos;&lt;Document6931a0a3-f94c-48e7-9162-195d5f10546f&gt;&apos; is not open.&#x000D;&#x000A;   at ShaderTools.CodeAnalysis.Workspace.CheckDocumentIsOpen(DocumentId documentId)&#x000D;&#x000A;   at ShaderTools.CodeAnalysis.Workspace.OnDocumentClosed(DocumentId documentId)&#x000D;&#x000A;   at ShaderTools.VisualStudio.LanguageServices.VisualStudioWorkspace.OnSubjectBufferDisconnected(ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at ShaderTools.VisualStudio.LanguageServices.WorkspaceBufferListener.SubjectBuffersDisconnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.WpfListener.SubjectBuffersDisconnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.&lt;&gt;c__DisplayClass8_1.&lt;Close&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by tgjones** [comment] 2019-07-29 13:29
I think it's a duplicate of #113 - I haven't released a new version since I fixed that. My current workflow is to close issues as soon as I fix them in master. I need to start using the changelog again to better communicate which issues have been fixed in which versions.

**Closed by tgjones** 2019-07-29 13:29 UTC
